#!/usr/bin/env python
import os, sys
from flask import *
from pymessenger import Bot

app =  Flask(__name__)

page_token = "EAAMPICslelkBAGx9IB7Gsx4UiPD4BDkb2tgX2w9pJ7mkBandiVk7A0sYRha1va9W1YD5g3Trc2SiIXQzDxVpvrotCdSMTGgn0Ll3FpvSm7OOJIYFtpXsWHlUTZC9Hm9kfYXIU2j2nL1Bp23m4OATVWO82COpDf24aXsJZB3gZDZD"
bot = Bot(page_token)


@app.route('/', methods=['GET'])
def verify():
    if request.args.get("hub.mode") == "subscribe" and request.args.get("hub.challenge"):
        if not request.args.get("hub.verify_token") == "hello":
            return "Verification token mismatch ", 403
        return request.args["hub.challenge"], 200
    return "Hello world", 200

@app.route('/', methods=['POST'])
def webhook():
    data = request.get_json()
    log(data)
    
    if data['object'] == 'page':
        for entry in data['entry']:
            for messaging_event in entry['messaging']:
                sendet_id = messaging_event['sender']['id']
                recipient_id = messaging_event['recipient']['id']

                if messaging_event.get('message'):
                    if 'text' in messaging_event['message']:
                        messaging_text = messaging_event['message']['text']
                    else:
                        messaging_text = 'no text'
                    
                    response = messaging_text
                    bot.send_text_message(sender_id, response)

    return "ok", 200

def log(message):
    print message,
    sys.stdout.flush()


if __name__ ==  "__main__":
    app.run(debug = True, port = 8080)



